apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: conmurphy-provider-jet-aci
spec:
  package: conmurphy/provider-jet-aci:v0.0.16
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 10
---
apiVersion: aci.jet.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: aci
spec:
  credentials:
    source: Secret
    secretRef:
      name: example-creds
      namespace: default
      key: credentials
---
apiVersion: v1
kind: Secret
metadata:
  name: example-creds
  namespace: default
type: Opaque
stringData:
  credentials: |
    {
      "username": "admin",
      "password": "password",
      "url":"https://apic_url",
      "insecure": "true"
    }
