### WITHOUT REFERENCES/DEPENDENCIES
apiVersion: applications.aci.jet.crossplane.io/v1alpha1
kind: Epg
metadata:
  name: web
spec:
  forProvider:
    description: "Managed with Crossplane Provider"
    name: web
    applicationProfileDn: uni/tn-crossplane/ap-website-no-ref
  providerConfigRef:
    name: aci