### WITHOUT REFERENCES/DEPENDENCIES

apiVersion: application.aci.jet.crossplane.io/v1alpha1
kind: Filter
metadata:
  name: allow-https
spec:
  forProvider:
    tenantDn: uni/tn-crossplane
    name: allow-https
  providerConfigRef:
    name: aci

---

apiVersion: application.aci.jet.crossplane.io/v1alpha1
kind: FilterEntry
metadata:
  name: https
spec:
  forProvider:
    name: https
    dFromPort: https
    dToPort: https
    etherT: ip
    prot: tcp
    stateful: "yes"
    filterDn: uni/tn-crossplane/flt-allow-https
  providerConfigRef:
    name: aci
  
---


apiVersion: applications.aci.jet.crossplane.io/v1alpha1
kind: Filter
metadata:
  name: allow-icmp
spec:
  forProvider:
    name: allow-icmp
    tenantDn: uni/tn-crossplane
  providerConfigRef:
    name: aci

---

apiVersion: applications.aci.jet.crossplane.io/v1alpha1
kind: FilterEntry
metadata:
  name: icmp
spec:
  forProvider:
    name: icmp
    etherT: ip
    prot: icmp
    stateful: "yes"
    filterDn: uni/tn-crossplane/flt-allow-icmp
  providerConfigRef:
    name: aci

