### WITHOUT REFERENCES/DEPENDENCIES

apiVersion: networks.aci.jet.crossplane.io/v1alpha1
kind: Subnet
metadata:
  name: "web-subnet"
spec:
  forProvider:
    parentDnRef: 
      name: web
    description: "Managed with Crossplane Provider"
    annotation: tag_subnet
    ip: 10.0.0.1/24
    preferred: "no"
    scope:
    - private
    - shared
    virtual: "yes"
  providerConfigRef:
    name: aci
    