apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xapps.aci.cisco.com
  labels:
    provider: provider-jet-aci
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: aci.jet.crossplane.io/v1alpha1
    kind: XApp
  resources:
  - name: applicationprofile
    base:
      apiVersion: applications.aci.jet.crossplane.io/v1alpha1
      kind: ApplicationProfile
      spec:
        forProvider:
          tenantDnRef: 
            name: crossplane-composition
          description: "Managed with Crossplane Provider Composite Resource"
          name: crossplane-composition
        providerConfigRef:
          name: aci
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.tenantName
      toFieldPath: spec.forProvider.tenantDnRef
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.applicationName
      toFieldPath: spec.forProvider.name
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.providerConfigRef
      toFieldPath: spec.providerConfigRef.name

