apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xapps.aci.jet.crossplane.io
spec:
  group: aci.jet.crossplane.io
  names:
    kind: XApp
    plural: xapps
  claimNames:
    kind: App
    plural: apps
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  tenantName:
                    type: string
                  applicationName:
                    type: string
                  applicationVrf:
                    type: string
                  applicationSubnet:
                    type: string
                  providerConfigRef:
                    type: string
                required:
                - tenantName
                - applicationName
                - providerConfigRef
            required:
            - parameters
