### WITH REFERENCES/DEPENDENCIES

apiVersion: networks.aci.jet.crossplane.io/v1alpha1
kind: BridgeDomain
metadata:
  name: "web"
spec:
  forProvider:
    name: "web"
    tenantDnRef: 
      name: crossplane-argocd
    relationFvRsCtxRef:
      name: prod
    description: "Managed with Crossplane Provider"
    annotation: tag_bd
    arpFlood: "no"
    bridgeDomainType: regular
    unicastRoute: "no"
    unkMacUcastAct: flood
    v6unkMcastAct: flood
  providerConfigRef:
    name: aci
    