apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane # name of the Argo CD application
  namespace: argocd
spec:
  project: default
  source:
    chart: three-tier-app
    repoURL: https://conmurphy.github.io/crossplane-example-app/packages/three-tier-app/
    targetRevision: 0.0.2
    helm:
      releaseName: three-tier-app
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane # namespace we created
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
