apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aci-website-application # name of the Argo CD application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/conmurphy/crossplane-example-app/ # change here with your repository url
    targetRevision: HEAD
    path: argocd/k8s-resources/applications
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd # namespace we created
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
