apiVersion: aci.jet.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: aci
spec:
  credentials:
    source: Secret
    secretRef:
      name: example-creds
      namespace: default
      key: credentials
